### ISSUE TITLE
startmitm.py报错

### ISSUE THREAD

**Issue by nu0l** [rev1si0n/lamda#13]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/54735907/198943881-bbcb5716-4fcd-4f69-9aac-0fce8fc10663.png">

```
sudo python3 -u startmitm.py localhost

Traceback (most recent call last):
  File "/Users//Tools/android/lamda/tools/startmitm.py", line 13, in <module>
    from lamda.client import *
  File "/opt/homebrew/lib/python3.9/site-packages/lamda/client.py", line 44, in <module>
    protos, services = grpc.protos_and_services("services.proto")
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/_runtime_protos.py", line 155, in protos_and_services
    return _call_with_lazy_import("protos_and_services", protobuf_path)
  File "/opt/homebrew/lib/python3.9/site-packages/grpc/_runtime_protos.py", line 58, in _call_with_lazy_import
    return fn(protobuf_path)
  File "/opt/homebrew/lib/python3.9/site-packages/grpc_tools/protoc.py", line 96, in _protos_and_services
    return (_protos(protobuf_path), _services(protobuf_path))
  File "/opt/homebrew/lib/python3.9/site-packages/grpc_tools/protoc.py", line 82, in _protos
    module = importlib.import_module(module_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/opt/homebrew/lib/python3.9/site-packages/grpc_tools/protoc.py", line 141, in exec_module
    importlib.import_module(module_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/opt/homebrew/lib/python3.9/site-packages/grpc_tools/protoc.py", line 125, in exec_module
    exec(code, module.__dict__)
  File "<string>", line 21, in <module>
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

```
mitmproxy --version

Mitmproxy: 9.0.0
Python:    3.9.12
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  macOS-12.6-arm64-arm-64bit
```

**Comment by rev1si0n** [comment]
1. 不使用 sudo 并重试
2. 尝试创建 virtualenv 并在虚拟环境中安装使用

如果问题继续，方便的话打包整个 virtualenv 或者贴出 `pip3 freeze`
