### ISSUE TITLE
Not run !

### ISSUE THREAD

**Issue by Rebootsa-Dev** [rev1si0n/lamda#17]
Tue Jan  3 05:32:37 2023 install cacert: C:\Users\xp4h/.mitmproxy\mitmproxy-ca-cert.pem
Traceback (most recent call last):
  File "C:\Users\xp4h\Desktop\Python\Tisting\frida\lamda\tools\startmitm.py", line 144, in <module>
    d.install_ca_certificate(ca)
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\lamda\client.py", line 1655, in install_ca_certificate
    return self.stub("Util").install_ca_certificate(certfile)
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\lamda\client.py", line 1020, in install_ca_certificate
    r = self.stub.installCACertificate(req)
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 343, in result
    raise self
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 343, in result
    raise self
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 343, in result
    raise self
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "C:\Users\xp4h\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1672713159.729000000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3261,"referenced_errors":[{"created":"@1672713159.729000000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"

**Comment by rev1si0n** [comment]
1. open http://device-ip:65000 in browser to ensure that lamda is running
2. turn off any of your system proxy
