### ISSUE TITLE
[ISSUE]老哥们遇到这种问题了吗

### ISSUE THREAD

**Issue by Core8light** [rev1si0n/lamda#55]
安装时很成功 用的python 3.9.17
Successfully installed asn1crypto-1.5.1 grpc-interceptor-0.14.2 grpcio-1.48.2 grpcio-tools-1.48.2 lamda-3.157 protobuf-3.20.3 setuptools-68.0.0 six-1.16.0
测试运行时出现
(nixiang2) core8light@bogon pythonProject % python -m lamda.client                 
Traceback (most recent call last):
  File "/Users/core8light/anaconda3/envs/nixiang2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/core8light/anaconda3/envs/nixiang2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/core8light/anaconda3/envs/nixiang2/lib/python3.9/site-packages/lamda/client.py", line 17, in <module>
    import grpc
  File "/Users/core8light/anaconda3/envs/nixiang2/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/core8light/anaconda3/envs/nixiang2/lib/python3.9/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
****ImportError: dlopen(/Users/core8light/anaconda3/envs/nixiang2/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease**'**

有老哥知道这个是啥原因吗

**Comment by Core8light** [comment]
运行环境是 m2的mac

**Comment by rev1si0n** [comment]
https://stackoverflow.com/questions/72620996/apple-m1-symbol-not-found-cfrelease-while-running-python-app

**Comment by Core8light** [comment]
> https://stackoverflow.com/questions/72620996/apple-m1-symbol-not-found-cfrelease-while-running-python-app

老哥能留个邮箱或者qq号吗

**Comment by rev1si0n** [comment]
mailto:ihaven0emmail@gmail.com
