### ISSUE TITLE
安装cryptography依赖报错，请问怎么解决

### ISSUE THREAD

**Issue by lvzhenbo** [rev1si0n/lamda#65]
日志
```
pip install -U lamda
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting lamda
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3f/fc/4cf877f641b8931f59b29947d41e9a8223b0c69f4414af8a55fb35e02019/lamda-5.6.tar.gz (83 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting grpcio-tools<1.60.0,>=1.35.0 (from lamda)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b8/62/bac5143fd2629d611c03832737040d1bb168ad52d59cab41131df0e06ead/grpcio-tools-1.59.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting grpc-interceptor<0.15.0,>=0.13.0 (from lamda)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/a6/15d7784d4cad3ec0278ecac2f26b9993356aab9afcd5fbe0dbe4c32b8e44/grpc_interceptor-0.14.2-py3-none-any.whl (17 kB)
Collecting grpcio<1.60.0,>=1.35.0 (from lamda)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/38/98/ca2cb5a81e0e2f3e3a00ebf91338fd3278ea0673e156a7ff2de30fe17113/grpcio-1.59.0.tar.gz (24.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cryptography>=35.0.0 (from lamda)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ef/33/87512644b788b00a250203382e40ee7040ae6fa6b4c4a31dcfeeaa26043b/cryptography-41.0.4.tar.gz (630 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Collecting setuptools>=61.0.0
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl (807 kB)
      Collecting wheel
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl (64 kB)
      Collecting cffi>=1.12
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/68/ce/95b0bae7968c65473e1298efb042e10cafc7bafc14d9e4f154008241c91d/cffi-1.16.0.tar.gz (512 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        Getting requirements to build wheel did not run successfully.
        exit code: 1

        [27 lines of output]
        Traceback (most recent call last):
          File "D:\msys64\ucrt64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "D:\msys64\ucrt64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "D:\msys64\ucrt64\lib\python3.11\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
            self.run_setup()
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\build_meta.py", line 341, in run_setup
            exec(code, locals())
          File "<string>", line 126, in <module>
          File "<string>", line 105, in uses_msvc
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
            self.initialize()
          File "C:\Users\29422\AppData\Local\Temp\pip-build-env-lj16g1eh\overlay\lib\python3.11\site-packages\setuptools\_distutils\_msvccompiler.py", line 246, in initialize
            raise DistutilsPlatformError(
        distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by rev1si0n** [comment]
第三方包错误，请在标准的 windows 环境中安装，不要使用 MSYS。
