### ISSUE TITLE
[ISSUE] 抓包工具报错

### ISSUE THREAD

**Issue by hackpwnpwn** [rev1si0n/lamda#66]
执行python3 -u startmitm.py 192.168.1.117后

Sat Oct 21 11:16:43 2023 install cacert: /Users/mac/.mitmproxy/mitmproxy-ca-cert.pem
Sat Oct 21 11:16:43 2023 set proxy: lamda:ddd346059f9@192.168.1.116:55759/all
Sat Oct 21 11:16:44 2023 --mode regular --ssl-insecure --proxyauth lamda:ddd346059f9 --web-port 54669 --no-rawtcp --listen-port 55759
Sat Oct 21 11:16:44 2023 press CONTROL + C to stop
Traceback (most recent call last):
  File "startmitm.py", line 194, in <module>
    proc.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/mitmproxy/tools/main.py", line 154, in mitmweb
    from mitmproxy.tools import web
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/mitmproxy/tools/web/__init__.py", line 1, in <module>
    from mitmproxy.tools.web import master
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/mitmproxy/tools/web/master.py", line 4, in <module>
    from mitmproxy import addons
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/mitmproxy/addons/__init__.py", line 14, in <module>
    from mitmproxy.addons import onboarding
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/mitmproxy/addons/onboarding.py", line 2, in <module>
    from mitmproxy.addons.onboardingapp import app
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/mitmproxy/addons/onboardingapp/__init__.py", line 3, in <module>
    from flask import Flask, render_template
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 19, in <module>
    from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/Users/mac/Library/Python/3.8/lib/python/site-packages/werkzeug/local.py)

**Comment by rev1si0n** [comment]
依赖问题，请自行解决（安装指定版本的库及其依赖库）
