### ISSUE TITLE
[ISSUE]python3 -u startmitm.py 192.168.*.*  .ServiceUnavailable: unavaliable

### ISSUE THREAD

**Issue by sevenblack3166** [rev1si0n/lamda#67]
**Describe the bug**
**请详细描述 BUG**
Wed Nov 15 16:35:47 2023 install cacert: /Users/Freedom/.mitmproxy/mitmproxy-ca-cert.pem
Traceback (most recent call last):
  File "/Volumes/WDC/lamda-5.0/tools/startmitm.py", line 148, in <module>
    d.install_ca_certificate(ca)
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/lamda/client.py", line 1691, in install_ca_certificate
    return self.stub("Util").install_ca_certificate(certfile)
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/lamda/client.py", line 1042, in install_ca_certificate
    r = self.stub.installCACertificate(req)
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc/_interceptor.py", line 216, in __call__
    response, ignored_call = self._with_call(request,
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc/_interceptor.py", line 257, in _with_call
    return call.result(), call
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc/_interceptor.py", line 126, in result
    raise self._exception
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc/_interceptor.py", line 241, in continuation
    response, call = self._thunk(new_method).with_call(
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc/_interceptor.py", line 266, in with_call
    return self._with_call(request,
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc/_interceptor.py", line 254, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/grpc_interceptor/client.py", line 92, in intercept_unary_unary
    return self.intercept(_swap_args(continuation), request, call_details)
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/lamda/client.py", line 277, in intercept
    self.raise_remote_exception(res)
  File "/Users/Freedom/.pyenv/versions/3.10.2/lib/python3.10/site-packages/lamda/client.py", line 292, in raise_remote_exception
    raise self.remote_exception(exception)
lamda.exceptions.ServiceUnavailable: unavaliable

使用命令 python3 -u startmitm.py 192.168.124.86 --mode upstream:192.168.36.11:7890 --dns 8.8.8.8
出现以上错误，之前是可以用的，不知道为什么，现在用不了了
**Generate statistics**
**生成BUG诊断日志**
[statistics.txt](https://github.com/rev1si0n/lamda/files/13362266/statistics.txt)

```bash
https://raw.githubusercontent.com/rev1si0n/lamda/master/tools/statistics.sh

# Download statistics.sh from this link via browser
# 通过浏览器从该链接下载 statistics.sh

adb push statistics.sh /data/local/tmp
sh /data/local/tmp/statistics.sh /data/local/tmp/arm64-v8a/bin/launch.sh --logfile=/data/local/tmp/server.log

# Then upload /sdcard/statistics.txt and /data/local/tmp/server.log to this ISSUE
# 随后在此 ISSUE 中附上 /sdcard/statistics.txt 以及 /data/local/tmp/server.log
```

**Comment by rev1si0n** [comment]
1. 安装7.0版本的LAMDA
2. 重启试试
3. 启动服务后请等待一会
4. 最近有没有新增过Magisk或者相关模块
5. 最近有没有安装过root隐藏或相关内容
6. 最近有没有在设备上使用其他逆向或者相关工具
