### ISSUE TITLE
远程桌面操作时鼠标点击位置与手机实际点击位置不对应

### ISSUE THREAD

**Issue by 941597815** [rev1si0n/lamda#85]
鼠标点击位置与手机实际点击位置有很大偏差，跟本没法操作手机

**Comment by rev1si0n** [comment]
如果你的手机是多分辨率的（进入 adb shell 执行命令 `wm size` 有两个大小就是），那么需要到设置里将屏幕设置为固定分辨率，不同手机设置项不同但是都有。

**Comment by 941597815** [comment]
分辨率是固定的，我用scrcpy连接手机是正常的，但网页中不行

![9N% @9EBJJE1~MXDCDLQ8IL](https://github.com/rev1si0n/lamda/assets/63088217/1319f267-4eb5-482f-83df-91d9a5babc0f)

**Comment by rev1si0n** [comment]
执行 `echo 'touch.backend=system' >>/data/usr/properties.local` 并重启设备

**Comment by 941597815** [comment]
这个问题得到已解决，但是我遇到新的问题

![_MG@H 9QSY0SSDRHJX{23C](https://github.com/rev1si0n/lamda/assets/63088217/120929ea-d408-4990-91d1-1989bab8853c)

执行这个代码后报错，并且远程桌面也停止了，服务貌似都寄了。下面是完整报错内容


C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\python.exe C:\Users\Lenovo\PycharmProjects\lamda\main.py 
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\lamda\main.py", line 5, in <module>
    d.beep()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\lamda\client.py", line 1924, in beep
    return self.stub("Util").beep()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\lamda\client.py", line 1325, in beep
    r = self.stub.beepBeep(protos.Empty())
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 1178, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.1.25:65000: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.1.25:65000: Connection refused {created_time:"2024-05-08T14:14:37.6286821+00:00", grpc_status:14}"
>

进程已结束，退出代码为 1

**Comment by rev1si0n** [comment]
使用其他接口呢，例如 `d.application("com.android.settings").start()`

**Comment by 941597815** [comment]
![A1V`8%WQ{KSM8A$DXN5R}5V](https://github.com/rev1si0n/lamda/assets/63088217/cd530ab1-5e45-4cc2-a274-3dcbefbb6ee8)
完整报错内容如下
C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\python.exe C:\Users\Lenovo\PycharmProjects\lamda\main.py 
Device@192.168.1.25:65000
Traceback (most recent call last):
  File "C:\Users\Lenovo\PycharmProjects\lamda\main.py", line 6, in <module>
    d.application("com.android.settings").start()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\lamda\client.py", line 1026, in start
    r = self.stub.startApplication(req)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 343, in with_call
    return self._with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 332, in _with_call
    return call.result(), call
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 438, in result
    raise self
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 1178, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.1.25:65000: socket is null"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.1.25:65000: socket is null {grpc_status:14, created_time:"2024-05-09T04:54:09.1886935+00:00"}"
>

进程已结束，退出代码为 1

**Comment by rev1si0n** [comment]
加群说吧
